- name: Enable non-islandora modules
  shell: "drush -y en {{ item }}"
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ non_islandora_modules }}"

- wait_for:
    port: 8080
    delay: 30

- name: enable islandora
  shell: "drush -y -u 1 en islandora"
  args:
    chdir: "{{drupal_core_path}}"

- name: Enable remaining islandora modules
  shell: "drush -y -u 1 en {{item}}"
  args:
    chdir: "{{drupal_core_path}}"
  with_items: "{{ modules_to_enable }}"

- name: Now that the module is downloaded and enabled, ensure that colorbox lib is downloaded and in place.
  shell: "drush -y -v colorbox-plugin"
  args:
    chdir: "{{drupal_core_path}}"
    creates: "{{libraries_dir}}/colorbox"
