---
- name: Cloning islandora modules
  git: clone=yes repo="https://github.com/islandora/{{item}}.git" dest="{{modules_dir}}/{{item}}" version=7.x update=no recursive=yes
  with_items: "{{ islandora_modules_to_clone }}"

- name: Set git config filemode off
  shell: git config core.filemode false
  args:
    chdir: "{{modules_dir}}/{{item}}"
  with_items: "{{ islandora_modules_to_clone }}"

  # in order to 'generate' features in place:
- name: ensure that sites/all/modules dir is writable by the web server
  file:
    state: directory
    owner: www-data
    recurse: yes
    path: "{{modules_dir}}"
  when: not subsite

- name: Get non-islandora modules
  shell: "drush dl -n {{ item }} "
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ non_islandora_modules }}"
