---
- name: Set variables for Islandora modules
  shell: "drush eval \"{{item}}\""
  args:
    chdir: "{{drupal_core_path}}"
  with_items:
    - "variable_set('islandora_audio_viewers', array('name' => array('none' => 'none', 'islandora_videojs' => 'islandora_videojs'), 'default' => 'islandora_videojs'))"
    - "variable_set('islandora_fits_executable_path', '{{fits_home}}/fits-{{fits_version}}/fits.sh')"
    - "variable_set('islandora_lame_url', '/usr/bin/lame')"
    - "variable_set('islandora_video_viewers', array('name' => array('none' => 'none', 'islandora_videojs' => 'islandora_videojs'), 'default' => 'islandora_videojs'))"
    - "variable_set('islandora_video_ffmpeg_path', '/usr/bin/ffmpeg')"
    - "variable_set('islandora_book_viewers', array('name' => array('none' => 'none', 'islandora_internet_archive_bookreader' => 'islandora_internet_archive_bookreader'), 'default' => 'islandora_internet_archive_bookreader'))"
    - "variable_set('islandora_book_page_viewers', array('name' => array('none' => 'none', 'islandora_openseadragon' => 'islandora_openseadragon'), 'default' => 'islandora_openseadragon'))"
    - "variable_set('islandora_large_image_viewers', array('name' => array('none' => 'none', 'islandora_openseadragon' => 'islandora_openseadragon'), 'default' => 'islandora_openseadragon'))"
    - "variable_set('islandora_use_kakadu', TRUE)"
    - "variable_set('islandora_newspaper_issue_viewers', array('name' => array('none' => 'none', 'islandora_internet_archive_bookreader' => 'islandora_internet_archive_bookreader'), 'default' => 'islandora_internet_archive_bookreader'))"
    - "variable_set('islandora_newspaper_page_viewers', array('name' => array('none' => 'none', 'islandora_openseadragon' => 'islandora_openseadragon'), 'default' => 'islandora_openseadragon'))"
    - "variable_set('islandora_pdf_create_fulltext', 1)"
    - "variable_set('islandora_checksum_enable_checksum', TRUE)"
    - "variable_set('islandora_ocr_tesseract', '/usr/bin/tesseract')"
    - "variable_set('islandora_batch_java', '/usr/bin/java')"
    - "variable_set('image_toolkit', 'imagemagick')"
    - "variable_set('imagemagick_convert', '/usr/bin/convert')"
    - "variable_set('bibutils_ris2xml_path', '/usr/bin/ris2xml')"
    - "variable_set('bibutils_endx2xml_path', '/usr/bin/endx2xml')"
    - "variable_set('islandora_metadata_display', 'islandora')"
