---

- name: Ensure that libraries directory exists.
  file:
    path: "{{ drupal_core_path }}/sites/all/libraries"
    state: directory
    owner: www-data
    group: www-data

- name: clone tuque
  git:
    clone: yes
    update: no
    repo: "https://github.com/Islandora/tuque.git"
    dest: "{{ drupal_core_path }}/sites/all/libraries/tuque"

- name: clone bagit lib
  git:
    clone: yes
    update: no
    repo: "https://github.com/scholarslab/BagItPHP.git"
    dest: "{{ drupal_core_path }}/sites/all/libraries/bagit"

- name: fmode
  shell: git config core.filemode false
  args:
    chdir: "{{ drupal_core_path }}/sites/all/libraries/tuque"

- name: fmode
  shell: git config core.filemode false
  args:
    chdir: "{{ drupal_core_path }}/sites/all/libraries/tuque"

- name: Make global drush commands dir for islandora
  file:
    path: /usr/local/share/drush/commands/islandora
    state: directory
    recurse: yes

- name: Copy libraries drush defs into global dir
  shell: "cp {{ drupal_core_path }}/sites/all/modules/{{item}} /usr/local/share/drush/commands/islandora/"
  with_items:
    - islandora_openseadragon/islandora_openseadragon.drush.inc
    - islandora_pdfjs/islandora_pdfjs.drush.inc
    - islandora_videojs/islandora_videojs.drush.inc
    - islandora_internet_archive_bookreader/islandora_internet_archive_bookreader.drush.inc

- name: Clear drush cache to register new commands.
  shell: drush cc drush
  args:
    chdir: '{{drupal_core_path}}'

- name: Ensure that unzip is available.
  apt:
    name: unzip

- name: Ensure that seadragon lib is downloaded and in place.
  unarchive:
    src: https://github.com/openseadragon/openseadragon/releases/download/v2.3.1/openseadragon-bin-2.3.1.zip
    dest: "{{ drupal_core_path }}/sites/all/libraries/"
    remote_src: yes

- name: symlink to version lib
  file:
    path: "{{ drupal_core_path }}/sites/all/libraries/openseadragon"
    src: "{{ drupal_core_path }}/sites/all/libraries/openseadragon-bin-2.3.1"
    state: link

# - name: Ensure that seadragon lib is downloaded and in place.
#   shell: "drush -y -v openseadragon-plugin"
#   args:
#     chdir: "{{drupal_core_path}}"
#     creates: "{{ drupal_core_path }}/sites/all/libraries/openseadragon"
#
