--- 
# Adapted from https://github.com/Islandora-Labs/islandora_vagrant/blob/master/scripts/devtools.sh

- apt: name=php-pear
- apt: name=doxygen

#- template: dest="/usr/local/bin/git-config" src=../templates/git-config.j2 mode=0755

# phploc
- stat: path=/usr/local/bin/phploc
  register: phploc

- get_url: url=https://phar.phpunit.de/phploc.phar dest=/usr/local/bin/phploc
- file: path=/usr/local/bin/phploc mode="0755" state=file 
  when: phploc.stat.exists == False

# phpcpd
- stat: path=/usr/local/bin/phpcpd
  register: phpcpd

- get_url: url=https://phar.phpunit.de/phpcpd.phar dest=/usr/local/bin/phpcpd
- file: path=/usr/local/bin/phpcpd mode="0755" state=file 
  when: phpcpd.stat.exists == False

# phpdepend
- stat: path=/usr/local/bin/pdepend
  register: pdepend

- get_url: 
    url: http://static.pdepend.org/php/latest/pdepend.phar
    dest: /usr/local/bin/pdepend
    validate_certs: False

- file: path=/usr/local/bin/pdepend mode="0755" state=file
  when: pdepend.stat.exists == False

# phpcb
- stat: path=/usr/local/bin/phpcb
  register: phpcb

- get_url:
    url: https://github.com/mayflower/PHP_CodeBrowser/releases/download/1.1.1/phpcb-1.1.1.phar 
    dest: /usr/local/bin/phpcb
  when: phpcb.stat.exists == False

- file: path=/usr/local/bin/phpcb mode="0755" state=file
  when: phpcb.stat.exists == False

# add a register/check thing here
- get_url: url=https://phar.phpunit.de/phploc.phar dest=/usr/local/bin/phploc

- stat: path=/usr/share/php/PHP/CodeSniffer
  register: phpcs_dir

- pear: name=PHP_CodeSniffer
  when: phpcs_dir.stat.exists == False

- name: Code Standards already exist
  stat: path=/usr/share/php/PHP/CodeSniffer/Standards/Drupal follow=yes
  register: cs_exist

- debug: var=cs_exist

- unarchive: src=http://ftp.drupal.org/files/projects/coder-8.x-2.1.tar.gz dest=/usr/share copy=no creates=/usr/share/coder
  when: cs_exist.stat.exists == False or cs_exist.stat.islnk == False 

- file: path=/usr/share/php/PHP/CodeSniffer/Standards/Drupal state=absent
#  when: (cs_exist.stat.exists == True and cs_exist.stat.islnk == False) or (cs_exist.stat.islnk == True and cs_exist.stat.lnk_source != "/usr/share/coder/coder_sniffer/Drupal")

# TODO figure out how to do this conditional without this error:
# "ERROR! The conditional check 'cs_exist.stat.islnk == False or (cs_exist.stat.islnk == True and cs_exist.stat.lnk_source != /usr/share/coder/coder_sniffer/Drupal)' failed. The error was: ERROR! template error while templating string: unexpected '/'"

- file: path=/usr/share/php/PHP/CodeSniffer/Standards/Drupal src=/usr/share/coder/coder_sniffer/Drupal state=link
#  when: cs_exist.stat.exists == False

###################
# xdebug
# - name: Install xdebug
#   apt:
#     name: php-xdebug
#   when: environment_type == 'dev'

# - name: Xdebug config
#   blockinfile:
#     dest: /etc/php/7.0/mods-available/xdebug.ini
#     block: |
#       [xdebug]
#       zend_extension=xdebug.so
#       xdebug.default_enable=1
#       xdebug.remote_enable=1
#       xdebug.remote_handler=dbgp
#       xdebug.remote_host={{ xdebug_remote_host }}
#       xdebug.remote_port=9000
#   when: environment_type == 'dev'