- name: Override default php settings
  template:
    src: 25-islandora.ini.j2
    dest: /etc/php5/apache2/conf.d/25-islandora.ini
    mode: 0644
    owner: root
    group: root
  notify: restart apache