---
- name: Insert proxy settings into vhost config
  blockinfile: 
    dest: /etc/apache2/sites-enabled/vhosts.conf
    regexp: '</Directory>\s*</VirtualHost>'
    insertafter: '</Directory>'
    block: |
            ProxyRequests Off
            ProxyPreserveHost On

            <Proxy "*"> 
            #    Order deny,allow 
            #    Allow from all 
            </Proxy>

            ProxyPass /fedora/get http://localhost:8080/fedora/get
            ProxyPassReverse /fedora/get http://localhost:8080/fedora/get 

            ProxyPass /fedora/services http://localhost:8080/fedora/services 
            ProxyPassReverse /fedora/services http://localhost:8080/fedora/services 

            ProxyPass /fedora/describe http://localhost:8080/fedora/describe  
            ProxyPassReverse /fedora/describe http://localhost:8080/describe 

            ProxyPass /iiv http://localhost:8080/iiv
            ProxyPassReverse /iiv http://localhost:8080/iiv

            ProxyPass /fedora/risearch http://localhost:8080/fedora/risearch 
            ProxyPassReverse /fedora/risearch http://localhost:8080/fedora/risearch

            ProxyPass /adore-djatoka http://localhost:8080/adore-djatoka
            ProxyPassReverse /adore-djatoka http://localhost:8080/adore-djatoka

            LogLevel debug

  notify: 
    - restart webserver
