---

- name: Create fits_home
  file: 
    path: "{{fits_home}}"
    state: directory

- name: Ensure unzip is installed
  apt: 
    name: unzip

- name: Check if fits source is cached locally
  stat:
    path: "{{ cache_dir }}/fits-{{fits_version}}.zip"
  register: fits_cached

- name: Fetch fits from cache.
  unarchive: 
    src: "{{ cache_dir }}/fits-{{fits_version}}.zip" 
    dest: "{{fits_home}}" 
    creates: "{{fits_home}}/fits-{{fits_version}}"
    copy: no
  when: fits_cached.stat.exists

- name: Download fits # this should only happen when fits is not cached.
  unarchive: 
    src: "http://projects.iq.harvard.edu/files/fits/files/fits-{{fits_version}}.zip" 
    dest: "{{fits_home}}" 
    creates: "{{fits_home}}/fits-{{fits_version}}"
    copy: no

- name: make fits.sh executable
  file: 
    path: "{{fits_home}}/fits-{{fits_version}}/fits.sh" 
    mode: 0755

- name: make fits-env.sh executable
  file: 
    path: "{{fits_home}}/fits-{{fits_version}}/fits-env.sh" 
    mode: 0755
